// apps/mobile/constants/mockChats.js
// Mock data for chat system development — replace with real API when backend is live

export const mockConversations = [
  {
    id: 'conv_1',
    type: 'DOCTOR_DOCTOR',
    participants: [
      {
        userId: 'doc_2',
        name: 'Dr. Anjali Mehta',
        role: 'doctor',
        specialty: 'Cardiologist, Apollo',
        avatarInitials: 'AM',
        avatarColor: '#7C3AED',
        online: true,
      },
    ],
    lastMessage: "Forwarding Priya's ECG — please review",
    lastMessageAt: new Date(Date.now() - 2 * 60000).toISOString(),
    unreadCount: 2,
  },
  {
    id: 'conv_2',
    type: 'DOCTOR_PATIENT',
    participants: [
      {
        userId: 'pat_1',
        name: 'Priya Sharma',
        role: 'patient',
        specialty: '32F · Hypertension',
        avatarInitials: 'PS',
        avatarColor: '#8B5CF6',
        online: false,
        lastSeen: '12m ago',
      },
    ],
    lastMessage: 'Doctor, should I take the medicine before meals?',
    lastMessageAt: new Date(Date.now() - 12 * 60000).toISOString(),
    unreadCount: 1,
  },
  {
    id: 'conv_3',
    type: 'DOCTOR_LAB',
    participants: [
      {
        userId: 'lab_1',
        name: 'Metropolis Labs',
        role: 'lab',
        specialty: 'Diagnostic Centre',
        avatarInitials: 'ML',
        avatarColor: '#F59E0B',
        online: true,
      },
    ],
    lastMessage: 'CBC + Lipid Panel report ready for Priya Sharma',
    lastMessageAt: new Date(Date.now() - 45 * 60000).toISOString(),
    unreadCount: 0,
  },
  {
    id: 'conv_4',
    type: 'DOCTOR_PHARMACY',
    participants: [
      {
        userId: 'pharm_1',
        name: 'MedPlus Pharmacy',
        role: 'pharmacy',
        specialty: 'MG Road Branch',
        avatarInitials: 'MP',
        avatarColor: '#22C55E',
        online: false,
        lastSeen: '1h ago',
      },
    ],
    lastMessage: 'Amlodipine 10mg is available, ready to dispense.',
    lastMessageAt: new Date(Date.now() - 70 * 60000).toISOString(),
    unreadCount: 0,
  },
]

export const mockMessages = {
  conv_1: [
    {
      id: 'msg_1',
      conversationId: 'conv_1',
      senderId: 'doc_2',
      type: 'TEXT',
      content: "Hi Dr. Rajan, I'm forwarding a case for your review.",
      status: 'read',
      reactions: [],
      createdAt: new Date(Date.now() - 10 * 60000).toISOString(),
    },
    {
      id: 'msg_2',
      conversationId: 'conv_1',
      senderId: 'doc_2',
      type: 'PATIENT_CARD',
      content: null,
      metadata: {
        patientName: 'Priya Sharma',
        age: 32,
        gender: 'F',
        diagnosis: 'Hypertension',
        lastBP: '158/98',
        medications: ['Amlodipine 5mg OD'],
        abhaVerified: true,
      },
      status: 'read',
      reactions: [],
      createdAt: new Date(Date.now() - 9 * 60000).toISOString(),
    },
    {
      id: 'msg_3',
      conversationId: 'conv_1',
      senderId: 'me',
      type: 'TEXT',
      content: "Got it, I'll take a look. Can you share the latest ECG as well?",
      status: 'delivered',
      reactions: [{ userId: 'doc_2', emoji: '👍' }],
      createdAt: new Date(Date.now() - 7 * 60000).toISOString(),
    },
    {
      id: 'msg_4',
      conversationId: 'conv_1',
      senderId: 'doc_2',
      type: 'LAB_REPORT',
      content: null,
      metadata: {
        title: 'Blood Panel + Lipid Profile',
        lab: 'Metropolis Labs',
        date: '12 May 2026',
        flag: 'Cholesterol: 218 (High)',
        patientName: 'Priya Sharma',
      },
      status: 'read',
      reactions: [],
      createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
    },
    {
      id: 'msg_5',
      conversationId: 'conv_1',
      senderId: 'doc_2',
      type: 'TEXT',
      content: "Forwarding Priya's ECG — please review",
      status: 'delivered',
      reactions: [],
      createdAt: new Date(Date.now() - 2 * 60000).toISOString(),
    },
  ],
  conv_2: [
    {
      id: 'msg_p1',
      conversationId: 'conv_2',
      senderId: 'me',
      type: 'TEXT',
      content: 'Hi Priya, your lab reports look good overall. Your BP was slightly elevated — please continue the medication.',
      status: 'read',
      reactions: [],
      createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
    },
    {
      id: 'msg_p2',
      conversationId: 'conv_2',
      senderId: 'me',
      type: 'PRESCRIPTION',
      content: null,
      metadata: {
        drugs: [
          { name: 'Amlodipine 5mg', dosage: '1-0-0', days: 30 },
          { name: 'Metformin 500mg', dosage: '1-0-1', days: 30 },
        ],
        doctor: 'Dr. Rajan',
        date: 'Today',
      },
      status: 'read',
      reactions: [],
      createdAt: new Date(Date.now() - 24 * 60000).toISOString(),
    },
    {
      id: 'msg_p3',
      conversationId: 'conv_2',
      senderId: 'pat_1',
      type: 'TEXT',
      content: 'Doctor, should I take the medicine before meals?',
      status: 'delivered',
      reactions: [],
      createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
    },
  ],
  conv_3: [
    {
      id: 'msg_l1',
      conversationId: 'conv_3',
      senderId: 'lab_1',
      type: 'TEXT',
      content: 'Good morning Dr. Rajan. We have received the blood draw for Priya Sharma.',
      status: 'read',
      reactions: [],
      createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
    },
    {
      id: 'msg_l2',
      conversationId: 'conv_3',
      senderId: 'lab_1',
      type: 'LAB_REPORT',
      content: null,
      metadata: {
        title: 'CBC + Lipid Panel',
        lab: 'Metropolis Labs',
        date: '14 May 2026',
        flag: 'LDL: 145 (Borderline High)',
        patientName: 'Priya Sharma',
      },
      status: 'read',
      reactions: [],
      createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    },
  ],
}
