import { $Enums } from '@prisma/client';

export { PrismaClient, Prisma, $Enums } from '@prisma/client';
export * from '@prisma/client';

export const Role = $Enums.Role;
export type Role = $Enums.Role;
export const UserStatus = $Enums.UserStatus;
export type UserStatus = $Enums.UserStatus;
export const ApprovalStatus = $Enums.ApprovalStatus;
export type ApprovalStatus = $Enums.ApprovalStatus;
export const OnboardingStatus = $Enums.OnboardingStatus;
export type OnboardingStatus = $Enums.OnboardingStatus;
export const SessionStatus = $Enums.SessionStatus;
export type SessionStatus = $Enums.SessionStatus;
export const ConsentStatus = $Enums.ConsentStatus;
export type ConsentStatus = $Enums.ConsentStatus;
export const ConsultationStatus = $Enums.ConsultationStatus;
export type ConsultationStatus = $Enums.ConsultationStatus;
export const ReportStatus = $Enums.ReportStatus;
export type ReportStatus = $Enums.ReportStatus;
export const Severity = $Enums.Severity;
export type Severity = $Enums.Severity;
export const ClinicalSource = $Enums.ClinicalSource;
export type ClinicalSource = $Enums.ClinicalSource;
export const StorageProvider = $Enums.StorageProvider;
export type StorageProvider = $Enums.StorageProvider;
export const FileCategory = $Enums.FileCategory;
export type FileCategory = $Enums.FileCategory;
export const RadiologyScanType = $Enums.RadiologyScanType;
export type RadiologyScanType = $Enums.RadiologyScanType;
export const AiJobStatus = $Enums.AiJobStatus;
export type AiJobStatus = $Enums.AiJobStatus;
export const PrescriptionStatus = $Enums.PrescriptionStatus;
export type PrescriptionStatus = $Enums.PrescriptionStatus;
export const AppointmentStatus = $Enums.AppointmentStatus;
export type AppointmentStatus = $Enums.AppointmentStatus;
export const AppointmentType = $Enums.AppointmentType;
export type AppointmentType = $Enums.AppointmentType;
export const UrgencyLevel = $Enums.UrgencyLevel;
export type UrgencyLevel = $Enums.UrgencyLevel;
export const ReminderChannel = $Enums.ReminderChannel;
export type ReminderChannel = $Enums.ReminderChannel;
export const ReminderStatus = $Enums.ReminderStatus;
export type ReminderStatus = $Enums.ReminderStatus;
export const RealtimeDeliveryStatus = $Enums.RealtimeDeliveryStatus;
export type RealtimeDeliveryStatus = $Enums.RealtimeDeliveryStatus;
